### ISSUE TITLE
Is Waterfox really portable?

### ISSUE THREAD

**Issue by angelog0** [portapps/waterfox-portable#23]
Just out of curiosity I tried this browser and noticed that it creates `Waterfox` folder in `[...]\AppData\Roaming` and `[...]\AppData\Local` folders. This is not good for an app which aims to be **portable**...

**Comment by crazy-max** [comment]
@angelog0 Thishas been fixed through `2020.05-15` with the addition od [`cleanup` setting](https://portapps.io/app/waterfox-portable/#configuration).

**Comment by mediocrenoob** [comment]
Not sure when this problem became a problem again but as of `waterfox-portable-win64-3.0.2-21-setup` it doesn't clean up the leftover folder in `appdata\roaming`
