### ISSUE TITLE
Portable package for Waterfox Current?

### ISSUE THREAD

**Issue by mzso** [portapps/waterfox-portable#35]
Hi!

Is there a chance for a portable version to be created for Waterfox current?

Classic is getting unusable. Some websites completely non-functioning. And others have broken features. (Probably mostly due to lack of HTML custom elements support)

**Comment by crazy-max** [comment]
Hi @mzso, I will move waterfox to "current" on the next release. Thanks for your input.

**Comment by crazy-max** [comment]
3.0.1 available: https://portapps.io/app/waterfox-portable/
