### ISSUE TITLE
Do webcams work in this browser?

### ISSUE THREAD

**Issue by idgas01** [portapps/waterfox-portable#40]
I have been using Waterfox Portable for around two months now, and I was not able to get webcams to work on one particular website that I can't share.   There is no point in saying what website that it is because I am a paid member on that website and the only way to use or test webcams on there is to become a paying member.  So anyway, I had this problem for two months on two different laptops.  Today, I decided to run some tests, but I couldn't find any good webcam chat room websites to test.  I visited two random ones, other than the one that I just mentioned.  I couldn't get my webcam to work on the first website, but it might have worked on the second website.  No way of knowing because I didn't ask anyone in the room "can you seem me?" because I got nervous and left.  So the website that I can't share won't even show my webcam image until I right click the window and select a different camera source like 'ManyCam'.  And then if I toggle back to 'HD User Facing' it will show my webcam image (instead of ManyCam's image).  But the top one third of the webcam will have a white box with the words "Connecting to videoXXXX..." where "XXXX" is a random number that it generates.  And it will just keep showing that connecting message and it never goes away.  On the first website that I visited today, I got this message "Failed to publish your stream.  Your system may not fully support this feature, or your browser may just need updating".  I am thinking that I should just ask you if you are able to successfully broadcat your own webcam in Waterfox Portable on multiple sites?  I want to understand what the problem might be and if there is anything that I can do to remedy it.  Or maybe it's a known or just now discovered bug and might be fixed in x number of months from now?

**Comment by crazy-max** [comment]
Should work with latest 3.0.1: https://portapps.io/app/waterfox-portable/

**Comment by idgas01** [comment]
Thank you @crazy-max.  Webcams seem to be working now.  But I can't believe how much Waterfox Portable has changed.  It really caught me off guard.  It looks very pretty, and looks nothing like I expected.  I'm running into two problems though.

1.) I was using this code in the userchrome.css
#nav-bar {display:none !important;}

But now if I use it, the web browser loads a blank page. I have to remove the #nav-bar code to make the web browser display websites.  I'll dig around in element picker later to see if I can use something different to accomplish the same thing.

@crazy-max, any chance you know how to hide the navigation bar?  You might know since you are smarter than me.

2.) Also, are legacy add-ons no longer working with Waterfox Portable.  That was one of the charms about using this browser is that older legacy add-ons was still compatible.  Are they gone now?  Forever?  I mean nothing I can do about it, so I won't complain.  I just want to know for sure.


Thanks.
