### ISSUE TITLE
Waterfox Portable switched to a different browser with last update.

### ISSUE THREAD

**Issue by Gitouisl** [portapps/waterfox-portable#44]
Waterfox Portable jumped from the Classic version (which is currently at [v2021.01](https://cdn.waterfox.net/releases/win64/portable/WaterfoxPortable_2021.01.1_English.paf.exe)) - which is made specifically to support legacy add-ons - to Waterfox's separate browser, [Waterfox Third Generation](https://www.waterfox.net/download/). So it's not a matter of opening an issue on the Waterfox repo as was the given solution to [closed issue #43](https://github.com/portapps/waterfox-portable/issues/43)- this portable actually changed apps to a completely different browser with the last update. It should be replaced with the continuation of the Waterfox Classic line, and Waterfox Third Generation should be a separate portable app, because it's a separate browser.

**Comment by crazy-max** [comment]
@Gitouisl I will create a branch derived from the latest Classic to handle that and to be able to deliver both. Keep you in touch.

**Comment by crazy-max** [comment]
Done
