### ISSUE TITLE
Leftover folders if cleanup = true

### ISSUE THREAD

**Issue by mediocrenoob** [portapps/waterfox-portable#51]
### Behaviour

Not sure when this problem became a problem again but as of waterfox-portable-win64-3.0.2-21-setup it doesn't clean up the leftover folders in `AppData\Roaming`, `AppData\LocalLow` and `C:\ProgramData`

#### Steps to reproduce this issue

1. Change `waterfox-portable.sample.yml` to `waterfox-portable.yml`
2. Edit `cleanup: false` to `true`
3. Launch and close Waterfox.
4. Find left over folders.

#### Expected behaviour

Setting the cleanup to true should clean up the folders.

#### Actual behaviour

Empty folders are left behind.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : waterfox-portable-win64-3.0.2-21-setup

**Operating system** : Windows 10 Pro x64

**Winver screenshot** :

![winver screesnshot](https://user-images.githubusercontent.com/16497141/109586196-c7e00400-7ad2-11eb-9497-0df588b477d4.png)

### Logs

[waterfox-portable.log](https://github.com/portapps/waterfox-portable/files/6065711/waterfox-portable.log)

**Comment by mediocrenoob** [comment]
To avoid making another issue post I'll add there are also registry keys left behind too:
`HKEY_CURRENT_USER\SOFTWARE\Waterfox Ltd.`
`HKEY_USERS\S-1-5-21-2425218180-468575447-1364550084-1001\SOFTWARE\Waterfox Ltd.`

**Comment by crazy-max** [comment]
@mediocrenoob Thanks for your feedback I will take a look.

**Comment by crazy-max** [comment]
@mediocrenoob 

> Empty folders are left behind.

Can you give me their paths? Thanks.

**Comment by crazy-max** [comment]
Fixed in latest release
