### ISSUE TITLE
Compatibility issues with Windows 10 1809

### ISSUE THREAD

**Issue by RaXorX** [portapps/waterfox-portable#55]
### Behaviour
Neither the installer nor the archive's Waterfox Portable exe runs. Going through the app's data folder and finding the main browser exe, the browser runs fine.

#### Steps to reproduce this issue

1. Download the installer or Portable archive. Extract the archive.
2. Run the app.
3. Nothing happens.

#### Expected behaviour

The app should start the browser.

#### Actual behaviour

Nothing happens.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 2021.06-24 Waterfox Classic

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 LTSC 1809

**Winver screenshot** : 
![image](https://user-images.githubusercontent.com/44987810/123520937-20b25880-d6d1-11eb-91e6-7d08b27be2e2.png)

### Logs

[waterfox-portable.log](https://github.com/portapps/waterfox-portable/files/6720444/waterfox-portable.log)

**Comment by crazy-max** [comment]
@RaXorX Can you try with the latest release? Thanks.
