### ISSUE TITLE
Please please update

### ISSUE THREAD

**Issue by Skrell** [portapps/waterfox-portable#56]
Big fan of your waterfox portable release.  Been using it for months now, but I don't see any way to update it.  I assume it involves you make an entire new release?

**Comment by nima-amin** [comment]
Etsy.com already displays a red bar on top of the site saying something of stopping supporting older vesions of my webbrowser by September 14th. This is definitely new. A possibilty to update might be nice. The allegedly "portable" version on the Waterfox website isn't portable at all - you can't even move it within the same computer without losing your entire configuration.

**Comment by crazy-max** [comment]
https://github.com/portapps/waterfox-portable/releases
