### ISSUE TITLE
Any plans to upgrade to the latest Waterfox version G4.0.3.1?

### ISSUE THREAD

**Issue by k-allika** [portapps/waterfox-portable#60]
I noticed that the latest Waterfox release (https://github.com/WaterfoxCo/Waterfox/releases?page=1) is G4.0.3.1, however, the portable version is 3.2.6. Any plans to update the portable version to the latest version?

**Comment by Skrell** [comment]
+1  !  Really hoping this project hasn't been abandoned!  k-allika, if you haven't done so you should also donate to help motivate the author!

**Comment by arkotro** [comment]
You can update very easy. 
Download last version of Waterfox, extract Waterfox.G4.0.5.1.Setup.exe with 7-zip.
Copy all contents from "core" folder to "app" folder.

**Comment by k-allika** [comment]
> You can update very easy. Download last version of Waterfox, extract Waterfox.G4.0.5.1.Setup.exe with 7-zip. Copy all contents from "core" folder to "app" folder.

This worked perfectly. Thanks. Closing the issue.

**Comment by HyperCriSiS** [comment]
Are you sure it still works portable and does not write anything to appdata or registry?

**Comment by ioc2e3** [comment]
> Are you sure it still works portable and does not write anything to appdata or registry?

Same question ...

.
