### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by askasys-code** [portapps/waterfox-portable#66]
1 year without updates. Should I migrate to Firefox portable?

**Comment by crazy-max** [comment]
Updated https://portapps.io/app/waterfox-portable/#download

**Comment by ioc2e3** [comment]
Looks abandoned ...

**Comment by gamesharkmike** [comment]
https://www.waterfox.net/download/
G6.0.7

https://portapps.io/app/waterfox-portable/#download
6.0.7-29

Heyyy :)

**Comment by ioc2e3** [comment]
> [https://www.waterfox.net/download/G6.0.7](https://www.waterfox.net/download/) _
> 
> https://portapps.io/app/waterfox-portable/#download 6.0.7-29
> 
> 嘿嘿:)

It’s really great ~~

.

**Comment by ioc2e3** [comment]
Here ( https://github.com/portapps/waterfox-portable )
Here ( https://github.com/huiaei/waterfox-portable )

Haven't updated for a while

.

**Comment by ioc2e3** [comment]
Here ( https://github.com/portapps/waterfox-portable ) and ( https://github.com/huiaei/waterfox-portable ) ...

Once again , haven't updated for while ...

.

**Comment by ioc2e3** [comment]
Here ( https://github.com/portapps/waterfox-portable ) and ( https://github.com/huiaei/waterfox-portable ) ...

Once again , haven't updated for while ...

.

**Comment by ioc2e3** [comment]
Bad news ...

Here ( https://github.com/huiaei/waterfox-portable ) ...

 It is now read-only ...

.

**Comment by ioc2e3** [comment]
Here ( https://github.com/portapps/waterfox-portable ) ...

Once again , haven't updated for while ...

Here ( https://github.com/huiaei/waterfox-portable ) ...

It is now read-only ...

.
