### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by Huiaei** [portapps/waterfox-portable#73]
Hi, I noticed that latest releases is still for June 2022. I am a person who likes to use the latest version and I think it's time to do an update after 6 months. I don't know when to update, so I tried forking the project and simply changed the download path and target version of the installer. But making a portapp was not as easy as I thought, and although it worked, I used Hibit Uninstaller's Installation Monitoring feature to find that some folders and registry remained after I quit waterfox, and I didn't know what to do with them.

I think this should belong in Discussions, but the project doesn't use it, so I posted Issue.

**Comment by ioc2e3** [comment]
It's already December...



Also waiting for the new version of Portable's Waterfox Browser...

**Comment by minus21grams** [comment]
Perhaps Crazy Max doesn’t see the _need_ to release an update. Most, if not all, of his portable apps are fully compatible with newer versions.
In Waterfox all you have to do is extract the contents of the original executable, rename "core" to "app" and overwrite the Portable app folder. It’s worked flawlessly so far (for Waterfox G5.x and G6.x)

**Comment by ioc2e3** [comment]
> Perhaps Crazy Max doesn’t see the need to release an update. Most, if not all, of his portable apps are fully compatible with newer versions.
> In Waterfox all you have to do is extract the contents of the original executable, rename "core" to "app" and overwrite the Portable app folder. It’s worked flawlessly so far (for Waterfox G5.x and G6.x)

Have failed even this step ...

.

**Comment by Huiaei** [comment]
> I don't know when to update, so I tried forking the project and simply changed the download path and target version of the installer. But making a portapp was not as easy as I thought, and although it worked, I used Hibit Uninstaller's Installation Monitoring feature to find that some folders and registry remained after I quit waterfox, and I didn't know what to do with them.

My temporary solution is to change [build.properties](https://github.com/Huiaei/waterfox-portable/commit/7c3b79c2327787b417c5ce62f7baebc4c2bf0e91#diff-e40833ed7fe7cbf5408b6b878877e7a030a56c3b0a3c724dc2c9bb2efcbe68d0).It is available, but as previously mentioned.

> I used Hibit Uninstaller's Installation Monitoring feature to find that some folders and registry remained after I quit waterfox.

It is unclear whether there are still residual files after the run, or it may be that the installation monitoring ended too quickly after the program ended, resulting in subsequent file movements not being recorded.

---

I have tried to make it run and upload it to Releases after completion, but I am not sure how it ran before. This temporarily ends with a failure. For now, I will download directly from Actions [waterfox-portable  ](https://github.com/Huiaei/waterfox-portable/actions/runs/6946667885), maybe I'll consider manually uploading Releases later
