### ISSUE TITLE
Please don't force "DisableAppUpdate" 

### ISSUE THREAD

**Issue by HyperCriSiS** [portapps/waterfox-portable#79]
Hi,

can you please change to not force "DisableAppUpdate = true"?
Before I used your Waterfox portable version I used another portable version which did not force this option.
It was never an issue to update Waterfox with the internal updater.

Thanks and regards
Hyper

**Comment by crazy-max** [comment]
Portapps doesn't have any internal updater.

**Comment by HyperCriSiS** [comment]
This worked with the Waterfox internal updater... But I can't use it because it is forced to be disabled...

**Comment by HyperCriSiS** [comment]
Hi,
it is still deactivated in the newest version. 

![waterfox_Y4UUALi24i](https://github.com/portapps/waterfox-portable/assets/11708192/b2a81be2-57d0-4ce8-880d-77a72488a0b8)

It would be really convenient to be able to use the internal Waterfox updater.
