### ISSUE TITLE
Latest portapps.exe [3.9.0] doesn't work on Windows 7 (waterfox-portable.exe)

### ISSUE THREAD

**Issue by Keklul404** [portapps/waterfox-portable#81]
### Behaviour
Previous version [4.1.2.1-28] works fine on Windows 7, but the newest portable waterfox release [6.0.7-29] which use portapps [3.9.0] doesn't work (the .exe doesn't even start, and no logs are created), this is about the .exe to launch Watefox, not the installation/extraction .exe.

Waterfox can still be launched, but not from the portapps.exe (waterfox-portable.exe), replacing this .exe with an older version (from [4.1.2.1-28] portapps [3.5.0] allow to do the trick, but its unsure if it will later cause troubles.

#### Steps to reproduce this issue

1. Start **waterfox-portable.exe** to start Waterfox with a Windows 7 OS.

#### Expected behaviour

It should start Waterfox.

#### Actual behaviour

It does nothing, insta stop (so fast that it doesn't even show on the Task Manager), no logs are created and Waterfox doesn't start.

### Configuration

waterfox-portable-win64-6.0.7-29.7z

Windows 7 Ultimate 64 bits SP1

**Comment by jahnson** [comment]
> Yes it does, that's why I said: **Waterfox can still be launched, but not from the portapps.exe (waterfox-portable.exe), replacing this .exe with an older version (from [4.1.2.1-28] portapps [3.5.0] allow to do the trick, but its unsure if it will later cause troubles.**
> 
> I do use Waterfox portable right now, with a recent Warterfox version and older portableapps.exe file.

Yes, I understand, but normally by showing the W7 logo the author intends to indicate that the application is compatible with W7, not that the user must mix and match components with another version to get it to work!

**Comment by crazy-max** [comment]
Sorry for the inconvenience but support for Windows 7 and 8 has been dropped as these OSes are EOL for quite some time.

**Comment by jahnson** [comment]
Thank you for your reply.
Did u know that Waterfox is one of the few browsers that actually does still run under W7?

-------- Original Message --------
On 11/11/24 20:03, CrazyMax wrote:
Sorry for the inconvenience but support for Windows 7 and 8 has been dropped as these OSes are EOL for quite some time.

**Comment by filler56789** [comment]
> Thank you for your reply. Did u know that Waterfox is one of the few browsers that actually does still run under W7?
> […](#)

Yes, he does know that. But he doesn't care, because he's lazy.
